/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HttpxServer {
  constructor(options?: HttpxServerOptions | undefined | null)
}

export declare class SocketServer {
  constructor()
}

export declare class TransportServer {
  constructor()
}

export interface HttpxServerOptions {

}
